site_name: Arquitectura Orientada a Servicios - Unidad 3
use_directory_urls: true
repo_url: https://github.com/misaelnieto/itm_2005_soa_u3/
site_description: Documentación de la Unidad 3 de la materia de Arquitectura Orientada a Servicios
site_author: Noe Nieto

nav:
  - Tutorial: 
    - Introducción: tutorial/index.md
    - Paso 1 - Winget: tutorial/winget.md
    - Paso 2 - Git: tutorial/git.md
    - Paso 3 - Repositorio: tutorial/repositorio.md
    - Paso 4 - UV: tutorial/uv.md
    - Paso 5 - Implementación: tutorial/implementacion.md
    - Paso 6 - Pruebas de integración: tutorial/pytest.md
    - Paso 7 - Analisis estatico: tutorial/ruff.md
    - Paso 8 - Documentación: tutorial/mkdocs.md
    - Paso 9 - Pull Request: tutorial/pr.md
  - Herramientas:
    - webservice: herramientas/webservice.md
  - Proyectos: servicios/index.md
theme:
  name: material
  language: es
  palette:
    scheme: slate
    primary: brown
  font:
    text: Noto Serif
    code: Ubuntu Mono
  icon:
    logo: material/puzzle
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - toc.integrate
    - navigation.top


markdown_extensions:
  - toc:
      permalink: "#"
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - mkdocs-click
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
- mkdocstrings:
    handlers:
      python:
        locale: es
        paths:
          - tests
          - app