name: Documentacion

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  docus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Set cache ID
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache 
          restore-keys: |
            mkdocs-material-
      - name: Instala uv
        uses: astral-sh/setup-uv@v5
      - name: Instala las dependencias
        run: uv sync --all-extras --dev
      - name: Construye la documentación
        run: uv run mkdocs gh-deploy --force

